
`ifndef AXI4LITE_SCOREBOARD_SV
`define AXI4LITE_SCOREBOARD_SV

//////////////////////////////////////////////////////////////////////////////////
// Class Name : axi4lite_scoreboard
// Description: AXI4-Lite Scoreboard
//
// Purpose:
//   - Receives actual transactions from the monitor
//   - Receives expected transactions from the reference model
//   - Compares both transaction streams
//   - Reports mismatches
//   - Tracks pass/fail statistics
//
// Architecture:
//
//                  Monitor
//                     |
//                     v
//              actual_fifo
//
// Reference Model
//        |
//        v
//   expected_fifo
//
//        Scoreboard
//             |
//             v
//   Compare Expected vs Actual
//
// Notes:
//   - In-order comparison model
//   - One expected transaction per actual transaction
//   - Suitable for AXI4-Lite single outstanding transactions
//
//////////////////////////////////////////////////////////////////////////////////

class axi4lite_scoreboard extends uvm_scoreboard;

   //--------------------------------------------------------------------------
   // Factory Registration
   //--------------------------------------------------------------------------

   `uvm_component_utils(axi4lite_scoreboard)

   //--------------------------------------------------------------------------
   // Analysis FIFOs
   //
   // actual_fifo: Receives transactions observed by monitor.
   //
   // expected_fifo: Receives transactions predicted by reference model.
   //
   // These FIFOs naturally decouple transaction arrival timing.
   //--------------------------------------------------------------------------

   uvm_tlm_analysis_fifo #(axi4lite_txn) actual_fifo;
   uvm_tlm_analysis_fifo #(axi4lite_txn) expected_fifo;

   //--------------------------------------------------------------------------
   // Statistics
   //
   // Used for end-of-test reporting.
   //--------------------------------------------------------------------------

   int unsigned total_compares;
   int unsigned passed_compares;
   int unsigned failed_compares;

   //--------------------------------------------------------------------------
   // Constructor
   //--------------------------------------------------------------------------

   function new(
      string name = "axi4lite_scoreboard",
      uvm_component parent = null   );

      super.new(name, parent);

   endfunction

   //--------------------------------------------------------------------------
   // Build Phase
   //
   // Creates analysis FIFOs and initializes statistics.
   //--------------------------------------------------------------------------

   virtual function void build_phase(    uvm_phase phase   );

      super.build_phase(phase);

      //-----------------------------------------------------------------------
      // FIFO receiving monitor transactions
      //-----------------------------------------------------------------------

      actual_fifo =new("actual_fifo", this);

      //-----------------------------------------------------------------------
      // FIFO receiving reference-model predictions
      //-----------------------------------------------------------------------

      expected_fifo =new("expected_fifo", this);

      //-----------------------------------------------------------------------
      // Reset statistics counters
      //-----------------------------------------------------------------------

      total_compares  = 0;
      passed_compares = 0;
      failed_compares = 0;

      `uvm_info(get_type_name(),"Scoreboard Build Phase Complete",UVM_LOW)

   endfunction

   //--------------------------------------------------------------------------
   // Run Phase
   //
   // Main comparison loop.
   //
   // Flow:
   //
   // Actual Transaction
   //         +
   // Expected Transaction
   //         ↓
   //      Compare
   //         ↓
   //      Pass/Fail
   //--------------------------------------------------------------------------

   virtual task run_phase(uvm_phase phase);

      axi4lite_txn actual_txn;
      axi4lite_txn expected_txn;

      forever begin

         //--------------------------------------------------------------------
         // Get Actual Transaction
         //
         // Generated by monitor.
         //--------------------------------------------------------------------

         actual_fifo.get(actual_txn);

         //--------------------------------------------------------------------
         // Get Expected Transaction
         //
         // Generated by reference model.
         //--------------------------------------------------------------------

         expected_fifo.get(expected_txn);

         total_compares++;

         //--------------------------------------------------------------------
         // Transaction Comparison
         //--------------------------------------------------------------------

         if(compare_txns(actual_txn,expected_txn))
         begin

            passed_compares++;

            `uvm_info(get_type_name(),$sformatf("COMPARE PASS [%0d]",
                  total_compares),UVM_HIGH)

         end
         else begin

            failed_compares++;

            //-----------------------------------------------------------------
            // Detailed mismatch report
            //-----------------------------------------------------------------

            `uvm_error(get_type_name(),$sformatf({"COMPARE FAIL [%0d]\n","EXPECTED : %s\n","ACTUAL   : %s"},
                  total_compares,expected_txn.convert2string(),actual_txn.convert2string()))

         end

      end

   endtask

   //--------------------------------------------------------------------------
   // compare_txns()
   //
   // Compares all relevant transaction fields.
   //
   // Checked Fields:
   //   - Transaction Type
   //   - Address
   //   - Data
   //   - Response
   //
   // Returns:
   //   1 -> Match
   //   0 -> Mismatch
   //--------------------------------------------------------------------------

   function bit compare_txns(

      axi4lite_txn actual,
      axi4lite_txn expected );

      //-----------------------------------------------------------------------
      // Transaction Type
      //-----------------------------------------------------------------------

      if(actual.txn_type != expected.txn_type)
         return 0;

      //-----------------------------------------------------------------------
      // Address
      //-----------------------------------------------------------------------

      if(actual.addr != expected.addr)
         return 0;

      //-----------------------------------------------------------------------
      // Data
      //-----------------------------------------------------------------------

      if(actual.data != expected.data)
         return 0;

      //-----------------------------------------------------------------------
      // Response
      //-----------------------------------------------------------------------

      if(actual.resp != expected.resp)
         return 0;

      //-----------------------------------------------------------------------
      // Transaction Match
      //-----------------------------------------------------------------------

      return 1;

   endfunction

   //--------------------------------------------------------------------------
   // Report Phase
   //
   // Generates final scoreboard summary.
   //
   // Displays:
   //   - Total comparisons
   //   - Pass count
   //   - Fail count
   //   - Pass percentage
   //--------------------------------------------------------------------------

   virtual function void report_phase(uvm_phase phase);

      real pass_percentage;

      super.report_phase(phase);

      //-----------------------------------------------------------------------
      // Calculate pass rate
      //-----------------------------------------------------------------------

      if(total_compares == 0)
         pass_percentage = 0.0;
      else
         pass_percentage =(100.0 * passed_compares) /total_compares;

      //-----------------------------------------------------------------------
      // Summary Report
      //-----------------------------------------------------------------------

      `uvm_info(get_type_name(),"===================================================",UVM_NONE)

      `uvm_info(get_type_name(),"              SCOREBOARD REPORT",UVM_NONE)

      `uvm_info(get_type_name(),"===================================================",UVM_NONE)

      `uvm_info(get_type_name(),$sformatf("Total Compares : %0d",total_compares),UVM_NONE )

      `uvm_info(get_type_name(),$sformatf("Passed         : %0d",
            passed_compares),UVM_NONE)

      `uvm_info(get_type_name(),$sformatf("Failed         : %0d",
            failed_compares),UVM_NONE)

      `uvm_info(get_type_name(),$sformatf("Pass Rate      : %0.2f%%",
            pass_percentage),UVM_NONE    )

      `uvm_info(get_type_name(),"===================================================",UVM_NONE)

      //-----------------------------------------------------------------------
      // Final Status
      //-----------------------------------------------------------------------

      if(failed_compares == 0)
      begin

         `uvm_info(get_type_name(),"*** SCOREBOARD PASSED ***",UVM_NONE)

      end
      else begin

         `uvm_error(get_type_name(),$sformatf("*** SCOREBOARD FAILED : %0d mismatches ***",
               failed_compares))

      end

   endfunction

endclass : axi4lite_scoreboard

`endif
